$create_table = 'CREATE TABLE gbif (
    id integer PRIMARY KEY,
    taxonID integer,
    datasetID varchar(300),
    parentNameUsageID varchar(100),
    acceptedNameUsageID varchar(100),
    originalNameUsageID varchar(100),
    scientificName varchar(300),
    scientificNameAuthorship varchar(300),
    canonicalName varchar(300),
    genericName varchar(300),
    specificEpithet varchar(300),
    infraspecificEpithet varchar(300),
    taxonRank varchar(50),
    nameAccordingTo varchar(50),
    namePublishedIn varchar(50),
    taxonomicStatus varchar(200),
    nomenclaturalStatus varchar(200),
    taxonRemarks text,
    kingdom varchar(200),
    phylum varchar(200),
    clazz varchar(200),
    ordder varchar(200),
    family varchar(200),
    genus varchar(200)
);'
